- src/OneLocBuildSample1/ClassLibrary1/Resource1.ko.resx
This is the pull request automatically created by the OneLocBuild task in the build process to check-in localized files generated based upon translation source files (.lcl files) handed-back from the downstream localization pipeline. If there are issues in translations, visit https://aka.ms/ceLocBug and log bugs for fixes. The wiki of the OneLocBuild task is https://aka.ms/onelocbuild and the localization process in general is documented at https://aka.ms/AllAboutLoc.
> Localized file check-in by OneLocBuild Task: Build definition ID 2805: Build ID 621459

- src/OneLocBuildSample1/ClassLibrary1/Resource1.ko.resx
> Localized file check-in by OneLocBuild Task: Build definition ID 5034: Build ID 899923

- src/OneLocBuildSample1/ClassLibrary1/Resource1.ko.resx
> Localized file check-in by OneLocBuild Task: Build definition ID 5034: Build ID 1008518

- src/OneLocBuildSample1/ClassLibrary1/Resource1.ko.resx
> Localized file check-in by OneLocBuild Task: Build definition ID 2805: Build ID 1012000

- src/OneLocBuildSample1/ClassLibrary1/Resource1.ko.resx
> Localized file check-in by OneLocBuild Task: Build definition ID 2805: Build ID 1122702

- src/OneLocBuildSample1/ClassLibrary1/Resource1.ko.resx
> Localized file check-in by OneLocBuild Task: Build definition ID 5034: Build ID 1142200

- Localize/loc/cs/src/OneLocBuildSample1/ClassLibrary1/Resource1.resx.lcl
- Localize/loc/de/src/OneLocBuildSample1/ClassLibrary1/Resource1.resx.lcl
- Localize/loc/es/src/OneLocBuildSample1/ClassLibrary1/Resource1.resx.lcl
- Localize/loc/fr/src/OneLocBuildSample1/ClassLibrary1/Resource1.resx.lcl
- Localize/loc/hu/src/OneLocBuildSample1/ClassLibrary1/Resource1.resx.lcl
- Localize/loc/it/src/OneLocBuildSample1/ClassLibrary1/Resource1.resx.lcl
- Localize/loc/ja/src/OneLocBuildSample1/ClassLibrary1/Resource1.resx.lcl
- Localize/loc/ko/src/OneLocBuildSample1/ClassLibrary1/Resource1.resx.lcl
- Localize/loc/nl/src/OneLocBuildSample1/ClassLibrary1/Resource1.resx.lcl
- Localize/loc/pl/src/OneLocBuildSample1/ClassLibrary1/Resource1.resx.lcl
- Localize/loc/pt-BR/src/OneLocBuildSample1/ClassLibrary1/Resource1.resx.lcl
- Localize/loc/pt-PT/src/OneLocBuildSample1/ClassLibrary1/Resource1.resx.lcl
- Localize/loc/ru/src/OneLocBuildSample1/ClassLibrary1/Resource1.resx.lcl
- Localize/loc/sv/src/OneLocBuildSample1/ClassLibrary1/Resource1.resx.lcl
- Localize/loc/tr/src/OneLocBuildSample1/ClassLibrary1/Resource1.resx.lcl
- Localize/loc/zh-Hans/src/OneLocBuildSample1/ClassLibrary1/Resource1.resx.lcl
- Localize/loc/zh-Hant/src/OneLocBuildSample1/ClassLibrary1/Resource1.resx.lcl
LEGO: Pull request from lego/hb_4556b5d5-6059-43af-a899-0a29bd7256da_20230104181859232 to main with localized lcls
> LEGO: Pull request from lego/hb_4556b5d5-6059-43af-a899-0a29bd7256da_20230104181859232 to main

- src/OneLocBuildSample1/ClassLibrary1/Resource1.ko.resx
> Localized file check-in by OneLocBuild Task: Build definition ID 5034: Build ID 1142287

- src/OneLocBuildSample1/ClassLibrary1/Resource1.ko.resx
> Localized file check-in by OneLocBuild Task: Build definition ID 5034: Build ID 1167449

- src/OneLocBuildSample1/ClassLibrary1/Resource1.ko.resx
> Localized file check-in by OneLocBuild Task: Build definition ID 5034: Build ID 1222370

- src/OneLocBuildSample1/ClassLibrary1/Resource1.ko.resx
> Localized file check-in by OneLocBuild Task: Build definition ID 5568: Build ID 1223285

- src/OneLocBuildSample1/ClassLibrary1/Resource1.ko.resx
> Localized file check-in by OneLocBuild Task: Build definition ID 5580: Build ID 1226372

- src/OneLocBuildSample1/ClassLibrary1/Resource1.ko.resx
> Localized file check-in by OneLocBuild Task: Build definition ID 2805: Build ID 1226451

- src/OneLocBuildSample1/ClassLibrary1/Resource1.ko.resx
> Localized file check-in by OneLocBuild Task: Build definition ID 5034: Build ID 1262444

- src/OneLocBuildSample1/ClassLibrary1/Resource1.ko.resx
> Localized file check-in by OneLocBuild Task: Build definition ID 2805: Build ID 1264218

- Localize/loc/ko/src/OneLocBuildSample1/ClassLibrary1/Resource1.resx.lcl
LCL file check-in from Loc Team's pipeline 5691, build 20230526.1
> LCL file check-in from Loc Team's pipeline 5691, build 20230526.1

- Localize/loc/ko-kr/code/Microsoft.AzureEmails/Templates/AAD/DomainAlert/DomainAlert.resx.lcl
- code/Microsoft.AzureEmails/Templates/AAD/DomainAlert/DomainAlert.de-de.resx
- code/Microsoft.AzureEmails/Templates/AAD/DomainAlert/DomainAlert.ko-kr.resx
Loc check-in of files from pipeline 5963, build 1515384
> Loc check-in of files from pipeline 5963, build 1515384

- code/Microsoft.AzureEmails/Templates/AAD/DomainAlert/DomainAlert.de-de.resx
- code/Microsoft.AzureEmails/Templates/AAD/DomainAlert/DomainAlert.ko-kr.resx
Loc check-in from pipeline 5963, build 1515390
> Loc check-in from pipeline 5963, build 1515390

- Localize/loc/ko-kr/code/Microsoft.AzureEmails/Templates/AAD/DomainAlert/DomainAlert.resx.lcl
- Localize/loc/ko-kr/code/Microsoft.AzureEmails/Templates/AAD/IdentityGovernance/AccessReview/RecurrentReportGenerated/RecurrentReportGenerated.resx.lcl
- Localize/loc/ko-kr/code/Microsoft.AzureEmails/Templates/AAD/IdentityGovernance/UserCentric/CompletionRbac/CompletionRbac.resx.lcl
- Localize/loc/ko-kr/code/Microsoft.AzureEmails/Templates/Batch/MFAPoliciesMultiple/MFAPoliciesMultiple.resx.lcl
- Localize/loc/ko-kr/code/Microsoft.AzureEmails/Templates/Commerce/Consumer/SubscriptionExpirationReminder/SubscriptionExpirationReminder.resx.lcl
Loc check-in from pipeline 5963, build 1515394
> Loc check-in from pipeline 5963, build 1515394

- Localize/loc/ko-kr/code/Microsoft.AzureEmails/Templates/AAD/DomainAlert/DomainAlert.resx.lcl
- Localize/loc/ko-kr/code/Microsoft.AzureEmails/Templates/AAD/IdentityGovernance/AccessReview/RecurrentReportGenerated/RecurrentReportGenerated.resx.lcl
- Localize/loc/ko-kr/code/Microsoft.AzureEmails/Templates/AAD/IdentityGovernance/UserCentric/CompletionRbac/CompletionRbac.resx.lcl
- Localize/loc/ko-kr/code/Microsoft.AzureEmails/Templates/Batch/MFAPoliciesMultiple/MFAPoliciesMultiple.resx.lcl
- Localize/loc/ko-kr/code/Microsoft.AzureEmails/Templates/Commerce/Consumer/SubscriptionExpirationReminder/SubscriptionExpirationReminder.resx.lcl
- code/Microsoft.AzureEmails/Templates/Commerce/Consumer/SubscriptionExpirationReminder/SubscriptionExpirationReminder.ar-sa.resx
LocFile Check-in from pipeline 5963, build 1516253
> LocFile Check-in from pipeline 5963, build 1516253

- Localize/loc/ko-kr/code/Microsoft.AzureEmails/Templates/AAD/DomainAlert/DomainAlert.resx.lcl
- Localize/loc/ko-kr/code/Microsoft.AzureEmails/Templates/AAD/IdentityGovernance/AccessReview/RecurrentReportGenerated/RecurrentReportGenerated.resx.lcl
- Localize/loc/ko-kr/code/Microsoft.AzureEmails/Templates/AAD/IdentityGovernance/UserCentric/CompletionRbac/CompletionRbac.resx.lcl
- Localize/loc/ko-kr/code/Microsoft.AzureEmails/Templates/Batch/MFAPoliciesMultiple/MFAPoliciesMultiple.resx.lcl
- Localize/loc/ko-kr/code/Microsoft.AzureEmails/Templates/Commerce/Consumer/SubscriptionExpirationReminder/SubscriptionExpirationReminder.resx.lcl
- code/Microsoft.AzureEmails/Templates/Commerce/Consumer/SubscriptionExpirationReminder/SubscriptionExpirationReminder.ar-sa.resx
LocFile Check-in from pipeline 5963, build 1517797
> LocFile Check-in from pipeline 5963, build 1517797

- code/Microsoft.AzureEmails/Templates/AAD/DomainAlert/DomainAlert.ko-kr.resx
LocFile Check-in from pipeline 5963, build 1520516
> LocFile Check-in from pipeline 5963, build 1520516
